CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Actors" (
    "ActorId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "Key" character varying(255) NOT NULL,
    "Type" character varying(255) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DisplayName" character varying(255) NOT NULL,
    "EmailAddress" character varying(255),
    "PictureUrl" character varying(2048),
    CONSTRAINT "PK_Actors" PRIMARY KEY ("ActorId")
);

CREATE TABLE "Aspects" (
    "AspectId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "MandatoryAttribute1" character varying(255),
    "MandatoryAttribute2" character varying(255),
    "OptionalAttribute1" character varying(255),
    "OptionalAttribute2" character varying(255),
    "DiscountedSkill1" character varying(255),
    "DiscountedSkill2" character varying(255),
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Aspects" PRIMARY KEY ("AspectId")
);

CREATE TABLE "Castes" (
    "CasteId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "Skill" character varying(255),
    "WealthRoll" character varying(255),
    "Features" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Castes" PRIMARY KEY ("CasteId")
);

CREATE TABLE "Customizations" (
    "CustomizationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "Type" character varying(255) NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Customizations" PRIMARY KEY ("CustomizationId")
);

CREATE TABLE "Educations" (
    "EducationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "Skill" character varying(255),
    "WealthMultiplier" double precision,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Educations" PRIMARY KEY ("EducationId")
);

CREATE TABLE "Languages" (
    "LanguageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "Script" character varying(255),
    "TypicalSpeakers" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("LanguageId")
);

CREATE TABLE "Talents" (
    "TalentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "Tier" integer NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "AllowMultiplePurchases" boolean NOT NULL,
    "RequiredTalentId" integer,
    "Skill" character varying(255),
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Talents" PRIMARY KEY ("TalentId"),
    CONSTRAINT "FK_Talents_Talents_RequiredTalentId" FOREIGN KEY ("RequiredTalentId") REFERENCES "Talents" ("TalentId") ON DELETE RESTRICT
);

CREATE TABLE "Natures" (
    "NatureId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "Attribute" character varying(255),
    "GiftId" integer,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Natures" PRIMARY KEY ("NatureId"),
    CONSTRAINT "FK_Natures_Customizations_GiftId" FOREIGN KEY ("GiftId") REFERENCES "Customizations" ("CustomizationId") ON DELETE RESTRICT
);

CREATE INDEX "IX_Actors_DisplayName" ON "Actors" ("DisplayName");

CREATE INDEX "IX_Actors_EmailAddress" ON "Actors" ("EmailAddress");

CREATE UNIQUE INDEX "IX_Actors_Id" ON "Actors" ("Id");

CREATE INDEX "IX_Actors_IsDeleted" ON "Actors" ("IsDeleted");

CREATE UNIQUE INDEX "IX_Actors_Key" ON "Actors" ("Key");

CREATE INDEX "IX_Actors_Type" ON "Actors" ("Type");

CREATE INDEX "IX_Aspects_CreatedBy" ON "Aspects" ("CreatedBy");

CREATE INDEX "IX_Aspects_CreatedOn" ON "Aspects" ("CreatedOn");

CREATE INDEX "IX_Aspects_DiscountedSkill1" ON "Aspects" ("DiscountedSkill1");

CREATE INDEX "IX_Aspects_DiscountedSkill2" ON "Aspects" ("DiscountedSkill2");

CREATE INDEX "IX_Aspects_DisplayName" ON "Aspects" ("DisplayName");

CREATE UNIQUE INDEX "IX_Aspects_Id" ON "Aspects" ("Id");

CREATE INDEX "IX_Aspects_MandatoryAttribute1" ON "Aspects" ("MandatoryAttribute1");

CREATE INDEX "IX_Aspects_MandatoryAttribute2" ON "Aspects" ("MandatoryAttribute2");

CREATE INDEX "IX_Aspects_OptionalAttribute1" ON "Aspects" ("OptionalAttribute1");

CREATE INDEX "IX_Aspects_OptionalAttribute2" ON "Aspects" ("OptionalAttribute2");

CREATE UNIQUE INDEX "IX_Aspects_StreamId" ON "Aspects" ("StreamId");

CREATE INDEX "IX_Aspects_UniqueSlug" ON "Aspects" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Aspects_UniqueSlugNormalized" ON "Aspects" ("UniqueSlugNormalized");

CREATE INDEX "IX_Aspects_UpdatedBy" ON "Aspects" ("UpdatedBy");

CREATE INDEX "IX_Aspects_UpdatedOn" ON "Aspects" ("UpdatedOn");

CREATE INDEX "IX_Aspects_Version" ON "Aspects" ("Version");

CREATE INDEX "IX_Castes_CreatedBy" ON "Castes" ("CreatedBy");

CREATE INDEX "IX_Castes_CreatedOn" ON "Castes" ("CreatedOn");

CREATE INDEX "IX_Castes_DisplayName" ON "Castes" ("DisplayName");

CREATE UNIQUE INDEX "IX_Castes_Id" ON "Castes" ("Id");

CREATE INDEX "IX_Castes_Skill" ON "Castes" ("Skill");

CREATE UNIQUE INDEX "IX_Castes_StreamId" ON "Castes" ("StreamId");

CREATE INDEX "IX_Castes_UniqueSlug" ON "Castes" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Castes_UniqueSlugNormalized" ON "Castes" ("UniqueSlugNormalized");

CREATE INDEX "IX_Castes_UpdatedBy" ON "Castes" ("UpdatedBy");

CREATE INDEX "IX_Castes_UpdatedOn" ON "Castes" ("UpdatedOn");

CREATE INDEX "IX_Castes_Version" ON "Castes" ("Version");

CREATE INDEX "IX_Customizations_CreatedBy" ON "Customizations" ("CreatedBy");

CREATE INDEX "IX_Customizations_CreatedOn" ON "Customizations" ("CreatedOn");

CREATE INDEX "IX_Customizations_DisplayName" ON "Customizations" ("DisplayName");

CREATE UNIQUE INDEX "IX_Customizations_Id" ON "Customizations" ("Id");

CREATE UNIQUE INDEX "IX_Customizations_StreamId" ON "Customizations" ("StreamId");

CREATE INDEX "IX_Customizations_Type" ON "Customizations" ("Type");

CREATE INDEX "IX_Customizations_UniqueSlug" ON "Customizations" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Customizations_UniqueSlugNormalized" ON "Customizations" ("UniqueSlugNormalized");

CREATE INDEX "IX_Customizations_UpdatedBy" ON "Customizations" ("UpdatedBy");

CREATE INDEX "IX_Customizations_UpdatedOn" ON "Customizations" ("UpdatedOn");

CREATE INDEX "IX_Customizations_Version" ON "Customizations" ("Version");

CREATE INDEX "IX_Educations_CreatedBy" ON "Educations" ("CreatedBy");

CREATE INDEX "IX_Educations_CreatedOn" ON "Educations" ("CreatedOn");

CREATE INDEX "IX_Educations_DisplayName" ON "Educations" ("DisplayName");

CREATE UNIQUE INDEX "IX_Educations_Id" ON "Educations" ("Id");

CREATE INDEX "IX_Educations_Skill" ON "Educations" ("Skill");

CREATE UNIQUE INDEX "IX_Educations_StreamId" ON "Educations" ("StreamId");

CREATE INDEX "IX_Educations_UniqueSlug" ON "Educations" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Educations_UniqueSlugNormalized" ON "Educations" ("UniqueSlugNormalized");

CREATE INDEX "IX_Educations_UpdatedBy" ON "Educations" ("UpdatedBy");

CREATE INDEX "IX_Educations_UpdatedOn" ON "Educations" ("UpdatedOn");

CREATE INDEX "IX_Educations_Version" ON "Educations" ("Version");

CREATE INDEX "IX_Languages_CreatedBy" ON "Languages" ("CreatedBy");

CREATE INDEX "IX_Languages_CreatedOn" ON "Languages" ("CreatedOn");

CREATE INDEX "IX_Languages_DisplayName" ON "Languages" ("DisplayName");

CREATE UNIQUE INDEX "IX_Languages_Id" ON "Languages" ("Id");

CREATE INDEX "IX_Languages_Script" ON "Languages" ("Script");

CREATE UNIQUE INDEX "IX_Languages_StreamId" ON "Languages" ("StreamId");

CREATE INDEX "IX_Languages_UniqueSlug" ON "Languages" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Languages_UniqueSlugNormalized" ON "Languages" ("UniqueSlugNormalized");

CREATE INDEX "IX_Languages_UpdatedBy" ON "Languages" ("UpdatedBy");

CREATE INDEX "IX_Languages_UpdatedOn" ON "Languages" ("UpdatedOn");

CREATE INDEX "IX_Languages_Version" ON "Languages" ("Version");

CREATE INDEX "IX_Natures_Attribute" ON "Natures" ("Attribute");

CREATE INDEX "IX_Natures_CreatedBy" ON "Natures" ("CreatedBy");

CREATE INDEX "IX_Natures_CreatedOn" ON "Natures" ("CreatedOn");

CREATE INDEX "IX_Natures_DisplayName" ON "Natures" ("DisplayName");

CREATE INDEX "IX_Natures_GiftId" ON "Natures" ("GiftId");

CREATE UNIQUE INDEX "IX_Natures_Id" ON "Natures" ("Id");

CREATE UNIQUE INDEX "IX_Natures_StreamId" ON "Natures" ("StreamId");

CREATE INDEX "IX_Natures_UniqueSlug" ON "Natures" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Natures_UniqueSlugNormalized" ON "Natures" ("UniqueSlugNormalized");

CREATE INDEX "IX_Natures_UpdatedBy" ON "Natures" ("UpdatedBy");

CREATE INDEX "IX_Natures_UpdatedOn" ON "Natures" ("UpdatedOn");

CREATE INDEX "IX_Natures_Version" ON "Natures" ("Version");

CREATE INDEX "IX_Talents_AllowMultiplePurchases" ON "Talents" ("AllowMultiplePurchases");

CREATE INDEX "IX_Talents_CreatedBy" ON "Talents" ("CreatedBy");

CREATE INDEX "IX_Talents_CreatedOn" ON "Talents" ("CreatedOn");

CREATE INDEX "IX_Talents_DisplayName" ON "Talents" ("DisplayName");

CREATE UNIQUE INDEX "IX_Talents_Id" ON "Talents" ("Id");

CREATE INDEX "IX_Talents_RequiredTalentId" ON "Talents" ("RequiredTalentId");

CREATE INDEX "IX_Talents_Skill" ON "Talents" ("Skill");

CREATE UNIQUE INDEX "IX_Talents_StreamId" ON "Talents" ("StreamId");

CREATE INDEX "IX_Talents_Tier" ON "Talents" ("Tier");

CREATE INDEX "IX_Talents_UniqueSlug" ON "Talents" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Talents_UniqueSlugNormalized" ON "Talents" ("UniqueSlugNormalized");

CREATE INDEX "IX_Talents_UpdatedBy" ON "Talents" ("UpdatedBy");

CREATE INDEX "IX_Talents_UpdatedOn" ON "Talents" ("UpdatedOn");

CREATE INDEX "IX_Talents_Version" ON "Talents" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250113221111_Release_0_1_0', '9.0.0');

COMMIT;
