START TRANSACTION;
CREATE TABLE "Specializations" (
    "SpecializationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "Tier" integer NOT NULL,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "RequiredTalentId" integer,
    "OtherRequirements" text,
    "OtherOptions" text,
    "ReservedTalentName" character varying(255),
    "ReservedTalentDescriptions" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Specializations" PRIMARY KEY ("SpecializationId"),
    CONSTRAINT "FK_Specializations_Talents_RequiredTalentId" FOREIGN KEY ("RequiredTalentId") REFERENCES "Talents" ("TalentId") ON DELETE RESTRICT
);

CREATE TABLE "SpecializationOptionalTalents" (
    "SpecializationId" integer NOT NULL,
    "TalentId" integer NOT NULL,
    CONSTRAINT "PK_SpecializationOptionalTalents" PRIMARY KEY ("SpecializationId", "TalentId"),
    CONSTRAINT "FK_SpecializationOptionalTalents_Specializations_Specializatio~" FOREIGN KEY ("SpecializationId") REFERENCES "Specializations" ("SpecializationId") ON DELETE CASCADE,
    CONSTRAINT "FK_SpecializationOptionalTalents_Talents_TalentId" FOREIGN KEY ("TalentId") REFERENCES "Talents" ("TalentId") ON DELETE CASCADE
);

CREATE INDEX "IX_SpecializationOptionalTalents_TalentId" ON "SpecializationOptionalTalents" ("TalentId");

CREATE INDEX "IX_Specializations_CreatedBy" ON "Specializations" ("CreatedBy");

CREATE INDEX "IX_Specializations_CreatedOn" ON "Specializations" ("CreatedOn");

CREATE INDEX "IX_Specializations_DisplayName" ON "Specializations" ("DisplayName");

CREATE UNIQUE INDEX "IX_Specializations_Id" ON "Specializations" ("Id");

CREATE INDEX "IX_Specializations_RequiredTalentId" ON "Specializations" ("RequiredTalentId");

CREATE INDEX "IX_Specializations_ReservedTalentName" ON "Specializations" ("ReservedTalentName");

CREATE UNIQUE INDEX "IX_Specializations_StreamId" ON "Specializations" ("StreamId");

CREATE INDEX "IX_Specializations_Tier" ON "Specializations" ("Tier");

CREATE INDEX "IX_Specializations_UniqueSlug" ON "Specializations" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Specializations_UniqueSlugNormalized" ON "Specializations" ("UniqueSlugNormalized");

CREATE INDEX "IX_Specializations_UpdatedBy" ON "Specializations" ("UpdatedBy");

CREATE INDEX "IX_Specializations_UpdatedOn" ON "Specializations" ("UpdatedOn");

CREATE INDEX "IX_Specializations_Version" ON "Specializations" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250116025836_Release_0_5_0', '9.0.0');

COMMIT;
